// Generated by tools/pack_animations.py. Do not edit manually.
#include "animation_definition.h"

// Source: src/assets/animations/spawn.anim.json
static const AnimKey SPAWN_SCALE_X_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 90, 1220, ANIM_EASE_OUT },
    { 180, 940, ANIM_EASE_IN_OUT },
    { 260, 1000, ANIM_EASE_IN },
};

static const AnimKey SPAWN_SCALE_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 90, 820, ANIM_EASE_OUT },
    { 180, 1080, ANIM_EASE_IN_OUT },
    { 260, 1000, ANIM_EASE_IN },
};

static const AnimKey SPAWN_ALPHA_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 50, 255, ANIM_EASE_OUT },
    { 260, 255, ANIM_EASE_LINEAR },
};

static const AnimTrack SPAWN_TRACKS[] = {
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = SPAWN_SCALE_X_KEYS,
        .key_count = sizeof(SPAWN_SCALE_X_KEYS) / sizeof(SPAWN_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = SPAWN_SCALE_Y_KEYS,
        .key_count = sizeof(SPAWN_SCALE_Y_KEYS) / sizeof(SPAWN_SCALE_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ALPHA,
        .keys = SPAWN_ALPHA_KEYS,
        .key_count = sizeof(SPAWN_ALPHA_KEYS) / sizeof(SPAWN_ALPHA_KEYS[0]),
    },
};

// Source: src/assets/animations/walk.anim.json
static const AnimKey WALK_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 120, 2, ANIM_EASE_OUT },
    { 240, -2, ANIM_EASE_IN_OUT },
    { 360, 2, ANIM_EASE_OUT },
    { 480, 0, ANIM_EASE_IN },
};

static const AnimKey WALK_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 120, 920, ANIM_EASE_OUT },
    { 240, 1120, ANIM_EASE_IN_OUT },
    { 360, 920, ANIM_EASE_OUT },
    { 480, 1000, ANIM_EASE_IN },
};

static const AnimKey WALK_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 120, 1100, ANIM_EASE_OUT },
    { 240, 900, ANIM_EASE_IN_OUT },
    { 360, 1100, ANIM_EASE_OUT },
    { 480, 1000, ANIM_EASE_IN },
};

static const AnimTrack WALK_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = WALK_OFFSET_Y_KEYS,
        .key_count = sizeof(WALK_OFFSET_Y_KEYS) / sizeof(WALK_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = WALK_SCALE_X_KEYS,
        .key_count = sizeof(WALK_SCALE_X_KEYS) / sizeof(WALK_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = WALK_SCALE_Y_KEYS,
        .key_count = sizeof(WALK_SCALE_Y_KEYS) / sizeof(WALK_SCALE_Y_KEYS[0]),
    },
};

const AnimationClip ANIMATION_CLIPS[] = {
    {
        .id = "spawn",
        .duration_ms = 260,
        .loop = false,
        .tracks = SPAWN_TRACKS,
        .track_count = sizeof(SPAWN_TRACKS) / sizeof(SPAWN_TRACKS[0]),
    },
    {
        .id = "walk",
        .duration_ms = 480,
        .loop = true,
        .tracks = WALK_TRACKS,
        .track_count = sizeof(WALK_TRACKS) / sizeof(WALK_TRACKS[0]),
    },
};

const uint8_t ANIMATION_CLIP_COUNT = sizeof(ANIMATION_CLIPS) / sizeof(ANIMATION_CLIPS[0]);
