#include "localization.h"

typedef struct {
    const char* english;
    const char* ukrainian;
} LocalizedText;

static const LocalizedText LOCALIZED_TEXTS[] = {
    [LOCALIZED_TEXT_APP_NAME] = {"CAT CHESS", "КОТОШАХИ"},
    [LOCALIZED_TEXT_NEW_GAME] = {"NEW GAME", "НОВА ГРА"},
    [LOCALIZED_TEXT_RESUME] = {"RESUME", "ПРОДОВЖИТИ"},
    [LOCALIZED_TEXT_RESTART] = {"RESTART", "ПОЧАТИ ЗАНОВО"},
    [LOCALIZED_TEXT_RELOAD] = {"RELOAD", "ОНОВИТИ"},
    [LOCALIZED_TEXT_PREVIOUS] = {"PREVIOUS", "ПОПЕРЕДНЯ"},
    [LOCALIZED_TEXT_NEXT] = {"NEXT", "ДАЛІ"},
    [LOCALIZED_TEXT_SETTINGS] = {"SETTINGS", "НАЛАШТУВАННЯ"},
    [LOCALIZED_TEXT_SETTINGS_SHORT] = {"SET", "ОПЦІЇ"},
    [LOCALIZED_TEXT_BACK] = {"BACK", "НАЗАД"},
    [LOCALIZED_TEXT_EXIT] = {"EXIT", "ВИХІД"},
    [LOCALIZED_TEXT_LEAVE_GAME] = {"LEAVE GAME?", "ВИЙТИ З ГРИ?"},
    [LOCALIZED_TEXT_YES] = {"YES", "ТАК"},
    [LOCALIZED_TEXT_NO] = {"NO", "НІ"},
    [LOCALIZED_TEXT_LANGUAGE] = {"LANGUAGE", "МОВА"},
    [LOCALIZED_TEXT_LANGUAGE_ENGLISH] = {"EN", "EN"},
    [LOCALIZED_TEXT_LANGUAGE_UKRAINIAN] = {"UK", "UK"},
    [LOCALIZED_TEXT_SFX] = {"SFX", "ЗВУКИ"},
    [LOCALIZED_TEXT_SOUNDS] = {"SOUNDS", "ЗВУКИ"},
    [LOCALIZED_TEXT_MUSIC] = {"MUSIC", "МУЗИКА"},
    [LOCALIZED_TEXT_HINTS] = {"HINTS", "ПІДКАЗКИ"},
    [LOCALIZED_TEXT_AI_DIFFICULTY] = {"AI DIFFICULTY", "СКЛАДНІСТЬ AI"},
    [LOCALIZED_TEXT_AI_EASY] = {"EASY", "ЛЕГКО"},
    [LOCALIZED_TEXT_AI_NORMAL] = {"NORMAL", "НОРМАЛЬНО"},
    [LOCALIZED_TEXT_AI_HARD] = {"HARD", "ВАЖКО"},
    [LOCALIZED_TEXT_ON] = {"ON", "УВІМК"},
    [LOCALIZED_TEXT_OFF] = {"OFF", "ВИМК"},
    [LOCALIZED_TEXT_GAME_OVER] = {"GAME OVER", "КІНЕЦЬ ГРИ"},
    [LOCALIZED_TEXT_GAME_START] = {"GAME START", "ПОЧАТОК ГРИ"},
    [LOCALIZED_TEXT_GAME_END] = {"GAME END", "КІНЕЦЬ ПАРТІЇ"},
    [LOCALIZED_TEXT_WHITE] = {"WHITE", "БІЛІ"},
    [LOCALIZED_TEXT_BLACK] = {"BLACK", "ЧОРНІ"},
    [LOCALIZED_TEXT_WHITE_TO_MOVE] = {"WHITE TO MOVE", "ХІД БІЛИХ"},
    [LOCALIZED_TEXT_BLACK_TO_MOVE] = {"BLACK TO MOVE", "ХІД ЧОРНИХ"},
    [LOCALIZED_TEXT_SELECT_PIECE] = {"SELECT PIECE", "ОБЕРІТЬ ФІГУРУ"},
    [LOCALIZED_TEXT_SELECT_TARGET] = {"SELECT TARGET", "ОБЕРІТЬ КЛІТИНКУ"},
    [LOCALIZED_TEXT_MOVE] = {"MOVE", "ХІД"},
    [LOCALIZED_TEXT_CAPTURE] = {"CAPTURE", "ВЗЯТТЯ"},
    [LOCALIZED_TEXT_ILLEGAL_MOVE] = {"ILLEGAL MOVE", "НЕДОПУСТИМИЙ ХІД"},
    [LOCALIZED_TEXT_CHECK] = {"CHECK", "ШАХ"},
    [LOCALIZED_TEXT_CHECKMATE] = {"CHECKMATE", "МАТ"},
    [LOCALIZED_TEXT_STALEMATE] = {"STALEMATE", "ПАТ"},
    [LOCALIZED_TEXT_DRAW] = {"DRAW", "НІЧИЯ"},
    [LOCALIZED_TEXT_CASTLE] = {"CASTLE", "РОКІРУВАННЯ"},
    [LOCALIZED_TEXT_PROMOTION] = {"PROMOTION", "ПЕРЕТВОРЕННЯ"},
    [LOCALIZED_TEXT_PROMOTE_TO] = {"PROMOTE TO", "ПЕРЕТВОРИТИ НА"},
    [LOCALIZED_TEXT_UNDO] = {"UNDO", "НАЗАД ХІД"},
    [LOCALIZED_TEXT_REDO] = {"REDO", "ПОВТОРИТИ"},
    [LOCALIZED_TEXT_PAWN] = {"PAWN", "ПІШАК"},
    [LOCALIZED_TEXT_KNIGHT] = {"KNIGHT", "КІНЬ"},
    [LOCALIZED_TEXT_BISHOP] = {"BISHOP", "СЛОН"},
    [LOCALIZED_TEXT_ROOK] = {"ROOK", "ТУРА"},
    [LOCALIZED_TEXT_QUEEN] = {"QUEEN", "ФЕРЗЬ"},
    [LOCALIZED_TEXT_KING] = {"KING", "КОРОЛЬ"},
    [LOCALIZED_TEXT_LOCAL_GAME] = {"LOCAL GAME", "ЛОКАЛЬНА ГРА"},
    [LOCALIZED_TEXT_ONLINE] = {"ONLINE", "ОНЛАЙН"},
    [LOCALIZED_TEXT_CREATE_ONLINE_GAME] = {"CREATE ONLINE", "СТВОРИТИ ОНЛАЙН"},
    [LOCALIZED_TEXT_JOIN_ONLINE_GAME] = {"JOIN ONLINE", "ПРИЄДНАТИСЯ"},
    [LOCALIZED_TEXT_MY_GAMES] = {"MY GAMES", "МОЇ ІГРИ"},
    [LOCALIZED_TEXT_CREATE_GAME] = {"CREATE GAME", "СТВОРИТИ ГРУ"},
    [LOCALIZED_TEXT_JOIN_GAME] = {"JOIN GAME", "ПРИЄДНАТИСЯ"},
    [LOCALIZED_TEXT_ONLINE_GAME] = {"ONLINE GAME", "ОНЛАЙН ГРА"},
    [LOCALIZED_TEXT_COMING_SOON] = {"COMING SOON", "НЕЗАБАРОМ"},
    [LOCALIZED_TEXT_SERVER_API_READY] = {"SERVER API READY", "API СЕРВЕРА ГОТОВЕ"},
    [LOCALIZED_TEXT_SERVER_READY] = {"SERVER READY", "СЕРВЕР ГОТОВИЙ"},
    [LOCALIZED_TEXT_SERVER_ERROR] = {"SERVER ERROR", "ПОМИЛКА СЕРВЕРА"},
    [LOCALIZED_TEXT_CONNECTING] = {"CONNECTING", "ПІДКЛЮЧЕННЯ"},
    [LOCALIZED_TEXT_GAME_CREATED] = {"GAME CREATED", "ГРУ СТВОРЕНО"},
    [LOCALIZED_TEXT_COPY_CODE] = {"COPY CODE", "КОПІЮВАТИ КОД"},
    [LOCALIZED_TEXT_NO_GAMES_YET] = {"NO GAMES YET", "ІГОР ЩЕ НЕМАЄ"},
    [LOCALIZED_TEXT_CREATE_ONLINE_PROMPT] = {"CREATE ONLINE GAME TO START", "СТВОРИ ОНЛАЙН ГРУ"},
    [LOCALIZED_TEXT_OPPONENT_TURN] = {"OPPONENT TURN", "ХІД СУПЕРНИКА"},
    [LOCALIZED_TEXT_WAITING_FOR_OPPONENT] = {"WAITING FOR OPPONENT", "ЧЕКАЄМО СУПЕРНИКА"},
    [LOCALIZED_TEXT_INVALID_CODE] = {"INVALID CODE", "НЕВІРНИЙ КОД"},
    [LOCALIZED_TEXT_GAME_NOT_FOUND] = {"GAME NOT FOUND", "ГРУ НЕ ЗНАЙДЕНО"},
    [LOCALIZED_TEXT_NETWORK_CLIENT_NOT_IMPLEMENTED] = {"NETWORK CLIENT NOT IMPLEMENTED", "МЕРЕЖЕВИЙ КЛІЄНТ НЕ ГОТОВИЙ"},
    [LOCALIZED_TEXT_NETWORK_CLIENT] = {"NETWORK CLIENT", "МЕРЕЖЕВИЙ КЛІЄНТ"},
    [LOCALIZED_TEXT_NOT_IMPLEMENTED] = {"NOT IMPLEMENTED", "НЕ ГОТОВИЙ"},
    [LOCALIZED_TEXT_INVITE_CODE] = {"INVITE CODE", "КОД ЗАПРОШЕННЯ"},
    [LOCALIZED_TEXT_GAME_ID] = {"GAME ID", "ID ГРИ"},
    [LOCALIZED_TEXT_STATUS] = {"STATUS", "СТАТУС"},
    [LOCALIZED_TEXT_YOUR_COLOR] = {"YOUR COLOR", "ВАШ КОЛІР"},
    [LOCALIZED_TEXT_SIDE_TO_MOVE] = {"SIDE TO MOVE", "ХТО ХОДИТЬ"},
    [LOCALIZED_TEXT_RESULT] = {"RESULT", "РЕЗУЛЬТАТ"},
    [LOCALIZED_TEXT_BOARD_FEN] = {"BOARD FEN", "FEN ДОШКИ"},
    [LOCALIZED_TEXT_MOVES] = {"MOVES", "ХОДИ"},
    [LOCALIZED_TEXT_CAPTURED] = {"CAPTURED", "ЗАХОПЛЕНО"},
    [LOCALIZED_TEXT_MOVE_FLOW] = {"MOVE FLOW", "ХІД ГРИ"},
    [LOCALIZED_TEXT_SEND_UCI_ONLY] = {"SEND UCI ONLY", "НАДСИЛАТИ ТІЛЬКИ UCI"},
    [LOCALIZED_TEXT_RESIGN] = {"RESIGN", "ЗДАТИСЯ"},
    [LOCALIZED_TEXT_WAITING_FOR_BLACK] = {"WAITING FOR BLACK", "ОЧІКУЄМО ЧОРНИХ"},
    [LOCALIZED_TEXT_ACTIVE] = {"ACTIVE", "АКТИВНА"},
    [LOCALIZED_TEXT_FINISHED] = {"FINISHED", "ЗАВЕРШЕНА"},
    [LOCALIZED_TEXT_NONE] = {"NONE", "НЕМАЄ"},
    [LOCALIZED_TEXT_UNKNOWN] = {"UNKNOWN", "НЕВІДОМО"},
    [LOCALIZED_TEXT_WHITE_WON] = {"WHITE WON", "БІЛІ ПЕРЕМОГЛИ"},
    [LOCALIZED_TEXT_BLACK_WON] = {"BLACK WON", "ЧОРНІ ПЕРЕМОГЛИ"},
    [LOCALIZED_TEXT_VS_COMPUTER] = {"VS COMPUTER", "ПРОТИ КОМП'ЮТЕРА"},
    [LOCALIZED_TEXT_THINKING] = {"THINKING", "ДУМАЮ"},
    [LOCALIZED_TEXT_YOUR_MOVE] = {"YOUR MOVE", "ВАШ ХІД"},
    [LOCALIZED_TEXT_AI_THINKING] = {"AI THINKING", "AI ДУМАЄ"},
    [LOCALIZED_TEXT_YOU_WIN] = {"YOU WIN", "ВИ ПЕРЕМОГЛИ"},
    [LOCALIZED_TEXT_YOU_LOSE] = {"YOU LOSE", "ВИ ПРОГРАЛИ"},
};

const char* localization_text(GameLocale locale, LocalizedTextId text_id) {
    if (text_id < 0 || (int)text_id >= (int)(sizeof(LOCALIZED_TEXTS) / sizeof(LOCALIZED_TEXTS[0]))) {
        return "";
    }

    if (game_settings_normalize_locale(locale) == GAME_LOCALE_UKRAINIAN) {
        return LOCALIZED_TEXTS[text_id].ukrainian;
    }

    return LOCALIZED_TEXTS[text_id].english;
}
