#ifndef CAT_CHESS_LOCALIZATION_H
#define CAT_CHESS_LOCALIZATION_H

#include "../settings/game_settings.h"

typedef enum {
    LOCALIZED_TEXT_APP_NAME = 0,
    LOCALIZED_TEXT_NEW_GAME,
    LOCALIZED_TEXT_RESUME,
    LOCALIZED_TEXT_RESTART,
    LOCALIZED_TEXT_SETTINGS,
    LOCALIZED_TEXT_BACK,
    LOCALIZED_TEXT_EXIT,
    LOCALIZED_TEXT_LANGUAGE,
    LOCALIZED_TEXT_LANGUAGE_ENGLISH,
    LOCALIZED_TEXT_LANGUAGE_UKRAINIAN,
    LOCALIZED_TEXT_SFX,
    LOCALIZED_TEXT_GAME_OVER,
    LOCALIZED_TEXT_GAME_START,
    LOCALIZED_TEXT_GAME_END,
    LOCALIZED_TEXT_WHITE,
    LOCALIZED_TEXT_BLACK,
    LOCALIZED_TEXT_WHITE_TO_MOVE,
    LOCALIZED_TEXT_BLACK_TO_MOVE,
    LOCALIZED_TEXT_SELECT_PIECE,
    LOCALIZED_TEXT_SELECT_TARGET,
    LOCALIZED_TEXT_MOVE,
    LOCALIZED_TEXT_CAPTURE,
    LOCALIZED_TEXT_ILLEGAL_MOVE,
    LOCALIZED_TEXT_CHECK,
    LOCALIZED_TEXT_CHECKMATE,
    LOCALIZED_TEXT_STALEMATE,
    LOCALIZED_TEXT_DRAW,
    LOCALIZED_TEXT_CASTLE,
    LOCALIZED_TEXT_PROMOTION,
    LOCALIZED_TEXT_PROMOTE_TO,
    LOCALIZED_TEXT_UNDO,
    LOCALIZED_TEXT_REDO,
    LOCALIZED_TEXT_PAWN,
    LOCALIZED_TEXT_KNIGHT,
    LOCALIZED_TEXT_BISHOP,
    LOCALIZED_TEXT_ROOK,
    LOCALIZED_TEXT_QUEEN,
    LOCALIZED_TEXT_KING,
    LOCALIZED_TEXT_LOCAL_GAME,
    LOCALIZED_TEXT_VS_COMPUTER,
    LOCALIZED_TEXT_THINKING,
    LOCALIZED_TEXT_YOU_WIN,
    LOCALIZED_TEXT_YOU_LOSE
} LocalizedTextId;

const char* localization_text(GameLocale locale, LocalizedTextId text_id);

#endif
